/**
 * src/lib/routeData.ts
 *
 * Route data helpers — Cloudflare Workers compatible.
 *
 * KEY CHANGE from the Vercel version:
 *   The original used `fs.readFileSync` to load routes.json lazily. That API
 *   does NOT exist in the Cloudflare Workers runtime. Instead we use dynamic
 *   `import()` of pre-split state-shard JSON files.
 *
 * Shard files (generated by `node scripts/split-routes.js`):
 *   src/data/routes-west-bengal.json   — 4,290 intra-WB routes
 *   src/data/routes-jharkhand.json     — 702 intra-JH routes
 *   src/data/routes-odisha.json        — 274 intra-OD routes
 *   src/data/routes-bihar.json         — 30 intra-BR routes
 *   src/data/routes-uttar-pradesh.json — 2 intra-UP routes
 *   src/data/routes-cross-wb.json      — 3,432 cross-state FROM WB
 *   src/data/routes-cross-jh.json      — 2,457 cross-state FROM JH
 *   src/data/routes-cross-od.json      — 1,717 cross-state FROM OD
 *   src/data/routes-cross-other.json   — 904 cross-state FROM BR/UP
 *
 * On a per-request basis the Worker only needs ALL shards for sitemap generation
 * and getRoute() lookups (which load all). Most pages need only 1-2 shards.
 *
 * IMPORTANT: JSON modules are bundled at build time by the edge bundler.
 *   The Workers free-tier 1MB limit applies to the *compiled JS bundle*, not
 *   to JSON data. JSON data loaded via dynamic import() goes into a separate
 *   chunk and does NOT count toward the 1MB Worker script limit.
 */
import 'server-only';
import { Route } from './data';

// ─── Shard keys ───────────────────────────────────────────────────────────────
const SHARD_KEYS = [
  'west-bengal',
  'jharkhand',
  'odisha',
  'bihar',
  'uttar-pradesh',
  'cross-wb',
  'cross-jh',
  'cross-od',
  'cross-other',
] as const;
type ShardKey = typeof SHARD_KEYS[number];

// In-memory shard cache — loaded once per Worker isolate lifetime
const shardCache = new Map<ShardKey, Route[]>();
let globalRouteMap: Map<string, Route> | null = null;
let allShardRoutes: Route[] | null = null;

async function loadShard(key: ShardKey): Promise<Route[]> {
  if (shardCache.has(key)) return shardCache.get(key)!;

  let data: Route[];
  switch (key) {
    case 'west-bengal':
      data = (await import('@/data/routes-west-bengal.json')).default as unknown as Route[];
      break;
    case 'jharkhand':
      data = (await import('@/data/routes-jharkhand.json')).default as unknown as Route[];
      break;
    case 'odisha':
      data = (await import('@/data/routes-odisha.json')).default as unknown as Route[];
      break;
    case 'bihar':
      data = (await import('@/data/routes-bihar.json')).default as unknown as Route[];
      break;
    case 'uttar-pradesh':
      data = (await import('@/data/routes-uttar-pradesh.json')).default as unknown as Route[];
      break;
    case 'cross-wb':
      data = (await import('@/data/routes-cross-wb.json')).default as unknown as Route[];
      break;
    case 'cross-jh':
      data = (await import('@/data/routes-cross-jh.json')).default as unknown as Route[];
      break;
    case 'cross-od':
      data = (await import('@/data/routes-cross-od.json')).default as unknown as Route[];
      break;
    case 'cross-other':
      data = (await import('@/data/routes-cross-other.json')).default as unknown as Route[];
      break;
    default:
      data = [];
  }
  shardCache.set(key, data);
  return data;
}

/** Load ALL shards and return the merged list + map. */
async function loadAllRoutes(): Promise<{ routes: Route[]; routeMap: Map<string, Route> }> {
  if (allShardRoutes && globalRouteMap) {
    return { routes: allShardRoutes, routeMap: globalRouteMap };
  }
  const shardArrays = await Promise.all(SHARD_KEYS.map(loadShard));
  const flat: Route[] = ([] as Route[]).concat(...shardArrays);
  const map = new Map<string, Route>(flat.map(r => [r.slug, r]));
  allShardRoutes = flat;
  globalRouteMap = map;
  return { routes: flat, routeMap: map };
}

// ─── Public async helpers ─────────────────────────────────────────────────────

export async function getAllRoutes(): Promise<Route[]> {
  return (await loadAllRoutes()).routes;
}

export async function getRoute(slug: string): Promise<Route | undefined> {
  return (await loadAllRoutes()).routeMap.get(slug);
}

export async function getRoutesFrom(citySlug: string): Promise<Route[]> {
  return (await loadAllRoutes()).routes.filter(r => r.from === citySlug);
}

export async function getRoutesTo(citySlug: string): Promise<Route[]> {
  return (await loadAllRoutes()).routes.filter(r => r.to === citySlug);
}

export async function getRoutesBetweenStates(fromState: string, toState: string): Promise<Route[]> {
  return (await loadAllRoutes()).routes.filter(
    r => r.fromState === fromState && r.toState === toState
  );
}

export async function getPopularRoutes(limit = 12): Promise<Route[]> {
  const { routes } = await loadAllRoutes();
  const hubSlugs = ['kolkata', 'ranchi', 'bhubaneswar'];
  const popularDestinations = new Set([
    'darjeeling', 'puri', 'digha', 'deoghar', 'konark', 'ranchi',
    'bhubaneswar', 'kolkata', 'jamshedpur', 'mandarmani', 'gangasagar',
    'mayapur', 'siliguri', 'durgapur', 'asansol', 'dhanbad', 'bokaro',
  ]);
  return routes
    .filter(r => hubSlugs.includes(r.from) && popularDestinations.has(r.to))
    .slice(0, limit);
}

export async function getLocalRoutes(citySlug: string, maxDistance = 200): Promise<Route[]> {
  return (await loadAllRoutes()).routes
    .filter(r => r.from === citySlug && r.distance <= maxDistance)
    .sort((a, b) => a.distance - b.distance);
}

export async function getPopularLocalRoutes(citySlug: string, limit = 8): Promise<Route[]> {
  const localRoutes = (await loadAllRoutes()).routes
    .filter(r => r.from === citySlug && r.distance <= 250 && r.distance > 0)
    .sort((a, b) => a.distance - b.distance);
  return localRoutes.slice(0, limit);
}

export async function getAllRouteSlugs(): Promise<string[]> {
  return (await loadAllRoutes()).routes.map(r => r.slug);
}

export async function getHighPriorityRoutes(): Promise<Route[]> {
  const { routes } = await loadAllRoutes();
  const hubSlugs = new Set(['kolkata', 'ranchi', 'bhubaneswar', 'jamshedpur', 'patna']);
  return routes.filter(r =>
    r.distance <= 250 || hubSlugs.has(r.from) || hubSlugs.has(r.to)
  );
}

export async function getLinkedRouteSlugs(): Promise<string[]> {
  const { routes, routeMap } = await loadAllRoutes();
  const hubSlugs = new Set(['kolkata', 'ranchi', 'bhubaneswar', 'jamshedpur', 'patna']);
  const seen = new Set<string>();

  routes.forEach(r => {
    if (r.distance <= 250 || hubSlugs.has(r.from) || hubSlugs.has(r.to)) {
      seen.add(r.slug);
    }
  });

  const routesByCity = new Map<string, Route[]>();
  for (const route of routes) {
    const list = routesByCity.get(route.from) ?? [];
    list.push(route);
    routesByCity.set(route.from, list);
  }
  for (const [, cityRoutes] of routesByCity) {
    cityRoutes.slice(0, 20).forEach(r => seen.add(r.slug));
    cityRoutes
      .filter(r => r.distance <= 250 && r.distance > 0)
      .sort((a, b) => a.distance - b.distance)
      .slice(0, 12)
      .forEach(r => seen.add(r.slug));
  }

  const finalSlugs = new Set<string>(seen);
  for (const slug of seen) {
    const parts = slug.split('-to-');
    if (parts.length === 2) {
      const reverseSlug = `${parts[1]}-to-${parts[0]}`;
      if (routeMap.has(reverseSlug)) finalSlugs.add(reverseSlug);
    }
  }
  return Array.from(finalSlugs);
}

export async function getLinkedVehicleRouteSlugs(): Promise<string[]> {
  const linked = await getLinkedRouteSlugs();
  return linked.filter(isHubRoute);
}

// ─── Pure synchronous helpers (no route data access needed) ───────────────────

export function isHubRoute(slug: string): boolean {
  const parts = slug.split('-to-');
  if (parts.length === 2) {
    const hubSlugs = new Set(['kolkata', 'ranchi', 'bhubaneswar', 'jamshedpur', 'patna']);
    return hubSlugs.has(parts[0]) || hubSlugs.has(parts[1]);
  }
  return false;
}


