/**
 * src/lib/routeData.ts
 *
 * Route data helpers — Cloudflare Workers compatible.
 *
 * Uses STATIC top-level imports so esbuild bundles the JSON directly into
 * handler.mjs at build time. Dynamic import() does NOT work in Workers runtime
 * because there's no filesystem to load from.
 *
 * The 9 state-shard JSON files are generated by: node scripts/split-routes.js
 */
import 'server-only';
import { Route } from './data';

// Static imports — bundled into handler.mjs by esbuild at build time
import rawWB from '@/data/routes-west-bengal.json';
import rawJH from '@/data/routes-jharkhand.json';
import rawOD from '@/data/routes-odisha.json';
import rawBH from '@/data/routes-bihar.json';
import rawUP from '@/data/routes-uttar-pradesh.json';
import rawCWB from '@/data/routes-cross-wb.json';
import rawCJH from '@/data/routes-cross-jh.json';
import rawCOD from '@/data/routes-cross-od.json';
import rawCOTH from '@/data/routes-cross-other.json';

// Merge all shards once at module load time (cached in isolate memory)
const ALL_ROUTES: Route[] = [
  ...(rawWB as unknown as Route[]),
  ...(rawJH as unknown as Route[]),
  ...(rawOD as unknown as Route[]),
  ...(rawBH as unknown as Route[]),
  ...(rawUP as unknown as Route[]),
  ...(rawCWB as unknown as Route[]),
  ...(rawCJH as unknown as Route[]),
  ...(rawCOD as unknown as Route[]),
  ...(rawCOTH as unknown as Route[]),
];

const ROUTE_MAP = new Map<string, Route>(ALL_ROUTES.map(r => [r.slug, r]));



// ─── Public async helpers ─────────────────────────────────────────────────────
// Kept async for backward compatibility with all call sites.

export async function getAllRoutes(): Promise<Route[]> {
  return ALL_ROUTES;
}

export async function getRoute(slug: string): Promise<Route | undefined> {
  return ROUTE_MAP.get(slug);
}

export async function getRoutesFrom(citySlug: string): Promise<Route[]> {
  return ALL_ROUTES.filter(r => r.from === citySlug);
}

export async function getRoutesTo(citySlug: string): Promise<Route[]> {
  return ALL_ROUTES.filter(r => r.to === citySlug);
}

export async function getRoutesBetweenStates(fromState: string, toState: string): Promise<Route[]> {
  return ALL_ROUTES.filter(r => r.fromState === fromState && r.toState === toState);
}

export async function getPopularRoutes(limit = 12): Promise<Route[]> {
  const hubSlugs = ['kolkata', 'ranchi', 'bhubaneswar'];
  const popularDestinations = new Set([
    'darjeeling', 'puri', 'digha', 'deoghar', 'konark', 'ranchi',
    'bhubaneswar', 'kolkata', 'jamshedpur', 'mandarmani', 'gangasagar',
    'mayapur', 'siliguri', 'durgapur', 'asansol', 'dhanbad', 'bokaro',
  ]);
  return ALL_ROUTES
    .filter(r => hubSlugs.includes(r.from) && popularDestinations.has(r.to))
    .slice(0, limit);
}

export async function getLocalRoutes(citySlug: string, maxDistance = 200): Promise<Route[]> {
  return ALL_ROUTES
    .filter(r => r.from === citySlug && r.distance <= maxDistance)
    .sort((a, b) => a.distance - b.distance);
}

export async function getPopularLocalRoutes(citySlug: string, limit = 8): Promise<Route[]> {
  return ALL_ROUTES
    .filter(r => r.from === citySlug && r.distance <= 250 && r.distance > 0)
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit);
}

export async function getAllRouteSlugs(): Promise<string[]> {
  return ALL_ROUTES.map(r => r.slug);
}



export async function getHighPriorityRoutes(): Promise<Route[]> {
  const hubSlugs = new Set(['kolkata', 'ranchi', 'bhubaneswar', 'jamshedpur', 'patna']);
  return ALL_ROUTES.filter(r =>
    r.distance <= 250 || hubSlugs.has(r.from) || hubSlugs.has(r.to)
  );
}


export async function getLinkedRouteSlugs(): Promise<string[]> {
  const hubSlugs = new Set(['kolkata', 'ranchi', 'bhubaneswar', 'jamshedpur', 'patna']);
  const seen = new Set<string>();

  ALL_ROUTES.forEach(r => {
    if (r.distance <= 250 || hubSlugs.has(r.from) || hubSlugs.has(r.to)) {
      seen.add(r.slug);
    }
  });

  const routesByCity = new Map<string, Route[]>();
  for (const route of ALL_ROUTES) {
    const list = routesByCity.get(route.from) ?? [];
    list.push(route);
    routesByCity.set(route.from, list);
  }
  for (const [, cityRoutes] of routesByCity) {
    cityRoutes.slice(0, 20).forEach(r => seen.add(r.slug));
    cityRoutes
      .filter(r => r.distance <= 250 && r.distance > 0)
      .sort((a, b) => a.distance - b.distance)
      .slice(0, 12)
      .forEach(r => seen.add(r.slug));
  }

  const finalSlugs = new Set<string>(seen);
  for (const slug of seen) {
    const parts = slug.split('-to-');
    if (parts.length === 2) {
      const reverseSlug = `${parts[1]}-to-${parts[0]}`;
      if (ROUTE_MAP.has(reverseSlug)) finalSlugs.add(reverseSlug);
    }
  }
  return Array.from(finalSlugs);
}

export async function getLinkedVehicleRouteSlugs(): Promise<string[]> {
  const linked = await getLinkedRouteSlugs();
  return linked.filter(isHubRoute);
}

// ─── Pure synchronous helpers (no route data access needed) ───────────────────

export function isHubRoute(slug: string): boolean {
  const parts = slug.split('-to-');
  if (parts.length === 2) {
    const hubSlugs = new Set(['kolkata', 'ranchi', 'bhubaneswar', 'jamshedpur', 'patna']);
    return hubSlugs.has(parts[0]) || hubSlugs.has(parts[1]);
  }
  return false;
}


